version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: db_postgres
    environment:
      POSTGRES_USER: thigga
      POSTGRES_PASSWORD: thigga
      POSTGRES_DB: thigga
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    
    volumes:
      - ./backend:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: thigga
      DB_USERNAME: thigga
      DB_PASSWORD: thigga
      APP_KEY: sua_chave_laravel 
      APP_DEBUG: "true"
    depends_on:
      - postgres


  nginx: 
    image: nginx:stable-alpine
    container_name: laravel_nginx_webserver
    restart: unless-stopped 
    ports: 
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002" # Porta para o Metro Bundler
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - backend

volumes:
  pgdata:
  node_modules_frontend: